### ISSUE TITLE
Slash is not optional when using multi parameters

### ISSUE THREAD

**Issue by goumang2010** [pillarjs/path-to-regexp#113]
My route is `/test/:cid(c\d+)?:uid(u\d+)?` ,  I want to match both `/test/` and `/test`,  it there any way to make it?  `/test` doesn't work right now.

**Comment by goumang2010** [comment]
The result is `/^\/test(?:\/(cd+))?(?:(ud+))?\/?$/i` with 0.1.x, which is good for this case, however, for 1.7.0, the result is `/^\/test\/((?:cd+))?(?:((?:ud+)))?(?:\/(?=$))?$/i` , it forced the trail slash

**Comment by blakeembrey** [comment]
To be honest, if this did work I don't think it'd be doing what you want it to. Would you want `/testu234` to match?

**Comment by blakeembrey** [comment]
The behaviour in 1.0 is intentional, FWIW. There are three test cases ensuring it acts how it does for specifically the reason above:

* `/:test?-bar`
* `/(apple-)?icon-:res(\\d+).png`
* `/:pre?baz`

If you disagree and you believe, for instance, that `/x-bar` or `-bar` (no `/` explicitly) should be the matching results, please share your reasoning. I'm not sure anyone would want that, even in your own case where you'd end up with `/testu982374` matching.

**Comment by goumang2010** [comment]
@blakeembrey Thanks for your reply. I do think `/testu982374` should not match `/test/:cid(c\d+)?:uid(u\d+)? ` . The slash is optional **only if all following stuff is optional**. For the example:
`foo/:test?-bar` ->   `foo/abc-bar` , `foo/-bar`
`foo/:test?(-bar)?` -> `foo/abc-bar` , `foo/-bar`,  `foo/`, `foo`
`foo/:test?(-bar)?-baz` -> `foo/abc-bar-baz` , `foo/-bar-baz`,  `foo/-baz`
`/test/:cid(c\d+)?:uid(u\d+)? ` -> `/test/c123u456`, `/test/c123`, `/test/u456`, `/test/`, `/test`

**Comment by blakeembrey** [comment]
This feels like an edge case and makes the parser more complex (right now it only needs to look a single character ahead, this proposal means you need to parse ahead and look behind to understand how the current token works). For this reason, if there's a simple PR you can make I'll look at it for 2.0 (no guarantees), but I'd propose that you just combine this into a single match (e.g. `/:cid(c\\d+|u\\d+|c\\d+u\\d+)` - this can even be simplified if you tackle https://github.com/pillarjs/path-to-regexp/issues/95). Right now token functionality is pretty clear (it only takes into account the prefix character), so I'd prefer to avoid the additional complexity.

You also need to consider the use case of token output _and_ path to string functions. With that functionality, I don't have a good idea of how that information would be efficiently encoded to ensure the output is always accurate (e.g. that `fn({ cid: 'u1', uid: 'u2' })` outputs `/test/c1u2` instead of `/test/c1/u2`). That'll take some investigation if you want to tackle this.

**Comment by blakeembrey** [comment]
I'm going to suggest an easy solution for your particular use-case. Use an array: `['/test', '/test/:cid(c\d+)?:uid(u\d+)?']`. I'm of the opinion that the current behaviour is the most correct approach of the three considered (1. always attach the prefix to the param, 2. attach only when it's the full segment, 3. attach when optional, or when preceding tokens are all optional). 

Your proposal is complicated because it requires an exponential number of attempts per optional tokens in a segment (e.g. your example _has_ to expand to `(?:\/(u\\d+)|\/(c\\d+)|\/(u\\d+)(c\\d+))?` to work). This is a _very_ bad idea, since now two parameters in the string have become four matching groups in the regexp and any module trying to match regexp matches to the keys is broken (because two results match up to a single key and ordering no longer matches user input). I don't see any other way for your proposal to work, but let me know if I overlooked it.

**Comment by blakeembrey** [comment]
By the way, 0.1.x doesn't work - it matches `/testu123`, which is not what you want.

**Comment by goumang2010** [comment]
Thanks for your suggestion.
