### ISSUE TITLE
Match at the beginning is not working in v2

### ISSUE THREAD

**Issue by frenzzy** [pillarjs/path-to-regexp#120]
```js
var pathToRegexp = require('path-to-regexp') // v2.0.0

var re1 = pathToRegexp('/', { end: true })  // => /^\/(?:\/(?=$))?$/i
var re2 = pathToRegexp('/', { end: false }) // => /^\/(?:\/(?=$))?$/i

re1.exec('/any') // => null
re2.exec('/any') // => null
```
Demo: https://runkit.com/frenzzy/pathtoregexp-v2-options-end

**Comment by blakeembrey** [comment]
This is intentional. See https://github.com/pillarjs/path-to-regexp/issues/116 and the changelog for more info. I'd consider `/` and `/any` siblings, not children.

**Comment by blakeembrey** [comment]
Where are you using this feature? Would it be clearer to use an empty string in non-ending mode?

**Comment by frenzzy** [comment]
For matching base paths and I think it is common use case. Yes, the use of an empty string is make sense. I see your reasons, thanks.

Could we add "strip trailing delimiter path match" option to avoid [the similar checks](https://github.com/pillarjs/path-to-regexp/blob/1bf805251c8486ea44395cd12afc37f77deec95e/index.js#L358-L366) on higher level?
```js
function stripLastDelimiter(path) {
  if (path instanceof RegExp) return path
  if (Array.isArray(path)) return path.map(p => p.replace(/\/$/, ''))
  return path.replace(/\/$/, '')
}

pathToRegexp(stripLastDelimiter(path), keys, options)
```

**Comment by blakeembrey** [comment]
> For matching base paths and I think it is common use case

Why do you believe it is common? Can you share where you're using this? 

It seems a little nonsensical to use `{ end: false }` with `/` and expect it to match everything, when you could save that computation and have a function that always returns true since it'll never not match in your preferred scenario. We can certainly add the behaviour back as a flag, but I'd like to understand how and why it's used first.

**Comment by frenzzy** [comment]
[Express Router](http://expressjs.com/en/guide/routing.html#express-router) use case:
```js
app.use('/base/path', routes) // { end: false }
```
```js
app.use(myMiddleware)
app.post('/login', myLoginRoute)
app.use('/', thirdPartyRoutes) // { end: false }
```

[Universal Router](https://github.com/kriasoft/universal-router) use case:

```js
const routes = [
  {
    path: '/base/path', // if base path match, then try to match children
    children: [
      { path: '/', action: () => 'Section' },          // => /base/path
      { path: '/child', action: () => 'Section Item' } // => /base/path/child
    ]
  }
  // ...
]
```
```js
const route = {
  path: '/', // or '' or '/admin' for just grouping routes with some common logic
  action({ next }) { // middleware fn
    // check auth
    return next() // try to match children
  }
  children: [
    { path: '/', action: () => 'Home' },
    { path: '/users', action: () => 'Users' }
  ]
}
```

https://github.com/kriasoft/universal-router/blob/7883e106cb850f89d68498bec24546f3c3d91bd2/src/matchPath.js#L28

**Comment by frenzzy** [comment]
The main question is how to match both urls with v2:
- `/birds/` => match, it is ok
- `/birds` => do not match, it is a problem, how to match it?
- `/birds/any` => do not match, it is ok
```js
var birds = express.Router()
birds.get('/', function (req, res) { // { end: true }
  res.send('Birds home page')
})

app.use('/birds', birds) // { end: false }
```

**Comment by blakeembrey** [comment]
@frenzzy Did you test that? Because it would definitely work. Express.js is based on 0.1 behaviour still, which didn't magically trim the trailing slash either. It just does an `|| '/'` so it'll replace empty strings with a single slash and it'll keep on matching. Your universal router use-case works the same also: https://github.com/kriasoft/universal-router/blob/7883e106cb850f89d68498bec24546f3c3d91bd2/src/matchPath.js#L48.

So both keep working the same, even though I'd recommend updating expectations in the future.

**Comment by frenzzy** [comment]
How to implement nested routes with v2?
For example:
```js
const route = {
  path: '/admin',
  children: [
    { path: '/', … },
    { path: '/users', … },
  ]
}
```
/admin/ => OK
/admin => 404

maybe `pathToRegexp('/')` must math both `'/'` and `''` ?

**Comment by blakeembrey** [comment]
> How to implement nested routes with v2?

Exactly the same as v1. I don't know that module/notation to help you, but no, it won't work like that with v2. Both modules you pointed out already handle this by falling back to `/` when the path is empty already. What's the concern you have?
