### ISSUE TITLE
undefined path names

### ISSUE THREAD

**Issue by Lobosque** [pillarjs/path-to-regexp#125]
Given the following code:
```
var pathToRegexp = require('path-to-regexp');
var re = pathToRegexp('/main/:module?/:category?/:subcategory?');
re.exec('/main//cat/sbucat');
```
I do not get a match (returns `null`).
I expect the following output:
```
[ '/main//cat/sbucat',
  undefined,
  'cat',
  'sbucat',
  index: 0,
  input: '/main//cat/sbucat' ]
```

Is there another way to get the match that I want? Since empty/undefined path names are valid in HTTP urls, I think it should match as in my example.

**Comment by blakeembrey** [comment]
It doesn't match because the slash is part of the optional match. You can get the match you want by using custom matching groups (https://github.com/pillarjs/path-to-regexp#custom-match-parameters) and not marking it as optional (since it's not optional in your example, the value can just be empty).
