### ISSUE TITLE
Support for matching anywhere inside a given url?

### ISSUE THREAD

**Issue by bstro** [pillarjs/path-to-regexp#127]
Imagine I have a URL that looks like `/foo/bar/baz/123`, but I only want to know about `baz/123`, baz indicating a collection i'm interested in, and `123` indicating a specific resource inside that collection. I don't need my code to be concerned with `foo` or `bar`, as that would couple this component to the route hierarchy in an undesirable way.

currently using `RE('/foo/bar/baz/:id').exec('/foo/bar/baz/123')`but like i said, this couples me to the entire hierarchy, where ideally my regexp would only be looking for `baz/:id`. Any thoughts?

Thanks!

**Comment by wesleytodd** [comment]
I assume you are asking this because you are using `path-to-regexp` outside of an express type application?  You could take a look at how the `router` module does this with the layers it builds up.  Either way I don't think moving more complicated functionality into this package is not a good idea.  It should be done in a wrapper like the express router does.

Router example: https://github.com/pillarjs/router/blob/master/index.js#L153-L338

**Comment by blakeembrey** [comment]
It is also possible to add an `start: false` flag to ignore pinning the match to the beginning. Would that help you?

(Feature subject to future investigation, but from the top of my head I see no issue - just needs handling like `end: false` does)

**Comment by ryanwalters** [comment]
A `start: false` flag is exactly what we need, would love to see that feature added.
