### ISSUE TITLE
Can not compile back parsed path

### ISSUE THREAD

**Issue by apsavin** [pillarjs/path-to-regexp#137]
Thanks for the library! It helps us a lot.

I have a case that can look like a bug from some point of view:

```js
const pathToRegexp = require('path-to-regexp');

const toPath = pathToRegexp.compile('/user/:path([\\w/-]+)');

toPath({ path: 'some-path' }); // /user/some-path
toPath({ path: 'some-path/with/delimiters' }); // exception
```

However, the string `/user/some-path/with/delimiters` will be correctly parsed.

I know, I can pass a custom encode function, but it's hard to do in general code of application (in fact, I don't use `path-to-regexp` directly, but through a router.).

Can we do something clever with this issue? Like, for example, do not encode parameters if parameter passes the regexp? Maybe, it's possible to provide the regexp into `encode` function so users will be able to do it on their side?

**Comment by blakeembrey** [comment]
The last suggestion definitely sounds reasonable - the encode function could be provided the "params" object like when decoding. What do you think? I haven't got a better idea today on how to handle it properly.

**Comment by apsavin** [comment]
Makes sense. Such "params" object can contain not only regexp, but also additional info (like, for example, a flag if custom regexp was provided for the parameter).

Can I help you somehow with the implementation?

**Comment by blakeembrey** [comment]
Just had another idea for a future version too. We could make a new "prefix" like `!path` to denote that it shouldn't be encoded or decoded. Open to better prefix suggestions.

**Comment by apsavin** [comment]
Sounds interesting, can solve my problem, too. But do we need an extra "prefix"? Can't we understand that we don't need to encode/decode by provided regexp?

**Comment by apsavin** [comment]
If, for example, only digits are allowed, then we don't need to encode/decode, validation is enough.

**Comment by blakeembrey** [comment]
It's not possible, no. Currently all values are always decoded by the implementation framework. Encoding has a similar issue. If the path is `/:foo(.*)`, you won't be able to send the same thing you received consistently (because it would have been decoded by the framework, turning `%2F` into `/` which conflicts with the input `/`). There'd need to be a way to say "keep it the way it came in".

**Comment by blakeembrey** [comment]
Also note, as your original post suggests, not every library implementation will likely expose a way to pass `encode` with a custom behaviour. How will consumers of these libraries indicate the intended behaviour with minimal overhead?

If we were to inspect the regexp, how would you decide if the regexp should encode or not? The value to encode is not actually dependent upon the regexp, but instead the data you put in. For instance, `?/%#` are all invalid URL characters by default (hence they're encoded). What if you don't want these encoded because you're reading the raw path for some reason or have unicode characters that you don't want to decode? Or rather, you're reading malformed/invalid params that just shouldn't be encoded/decoded when sent in the URL.

It's a tricky situation and allowing a simple escape hatch seemed the easiest solution.

**Comment by blakeembrey** [comment]
This should be supported already, you can use `encode: x => x` and `validate: false` to have the output feed directly back into the input of `compile`. However, you probably want to use `match` directly in the next major release, it'll split apart your paths how you want it.
