### ISSUE TITLE
tokensToRegExp signature

### ISSUE THREAD

**Issue by plandem** [pillarjs/path-to-regexp#144]
looks like signature for 'tokensToRegExp' was changed, but at readme there is still previous version - without keys parameter. Looks like breaking backward compatibility change

**Comment by blakeembrey** [comment]
Just a documentation issue, feel free to submit a PR. Ref: https://github.com/pillarjs/path-to-regexp/blob/master/History.md#200--2017-08-23. I don't understand what you mean when you say "looks like breaking backward compatibility change".

**Comment by plandem** [comment]
previously it was optional, because you could call it using “options” as second argument, now it’s required, if you want to pass options. so it’s breaking change, my previous code is not working anymore, because of this.

**Comment by blakeembrey** [comment]
That's why it was released in 2.0.0 though, is there something I missed?

**Comment by plandem** [comment]
yep, that's why I wrote it was 'breaking backward compatibility change'.

Previously this one was working fine:
```js
tokensToRegExp(tokens, options)
```
now you have to replace it with:
```js
tokensToRegExp(tokens, [], options)
```

so second 'keys' parameter is REQUIRED now and that's breaking backward compatibility change. It would be nice to update the history too (I read documentation and history few times to find about breaking changes). Because I had to search the code to get that signature of function was changed.


p.s.: also at history there is something about 'remove asterk logic', but at documentation there are some asteriks. Probably this part of documentation must be fixed too, but I'm not sure - don't use asteriks, so no use cases to test.

**Comment by frenzzy** [comment]
@plandem have you heard about [Semantic Versioning](https://semver.org/spec/v2.0.0.html)?

**Comment by plandem** [comment]
@frenzzy My original topic started with outdated documentation. My last message is still related to documentation. So go troll somewhere else.

**Comment by frenzzy** [comment]
@plandem if [the changelog](https://github.com/pillarjs/path-to-regexp/blob/v2.1.0/History.md) contained something like this:

> 2.0.0 / 2017-08-23
> ==================
> - [BREAKING] `tokensToRegExp(tokens, options)` => `tokensToRegExp(tokens, keys?, options?)`
> - [BREAKING] Remove asterisk functionality (it's a real pain to properly encode)
> - other changes

would it be helpful for you? maybe create a PR?

**Comment by plandem** [comment]
Kid, go do your lessons. If you can't read, then I will repeat specially for you:
`also at history there is something about 'remove asterk logic', but at documentation there are some asteriks. Probably this part of documentation must be fixed too, but I'm not sure - don't use asteriks, so no use cases to test.`

Here is your homework - find `Probably this part of documentation must be fixed too` and think about it  at least for few seconds. And for smartest one, here is additional task (sorry, repeat myself again) - find `but I'm not sure - don't use asteriks, so no use cases to test.` and think what you can do better, especially if you know how.

**Comment by blakeembrey** [comment]
@plandem There's no need for you to act like this. @frenzzy was checking with you because it was probably unclear for the both of us what was wrong with backward compatibility. That change was released in a major version according to semantic versioning because it specifically did break backward compatibility so I was initially confused about what you were asking there. 

@frenzzy's suggestion for updating the history docs was actually a really good one, I usually split my changes into three sections called "fixed", "changed" and "added" for that, but specifically emboldening **[Breaking]** sounds good too. 

As for the asterisk functionality, it's mentioned in https://github.com/pillarjs/path-to-regexp#compatibility-with-express--4x. Specifically it's `/*` that used to work.

Please don't come back here with your attitude either, everyone here is doing this work for free and just trying to help clarify things. It's likely there's a language barrier here also, so you need to ensure you provide as much detail as possible to you get the response you're looking for.

**Comment by blakeembrey** [comment]
Also feel free to submit a PR for what you'd like to clarify in https://github.com/pillarjs/path-to-regexp/blob/master/History.md#200--2017-08-23, I agree it could use better examples and more explicit call outs to the breaking changes.

**Comment by blakeembrey** [comment]
That's the case, you can't use `*` as a standalone wildcard (for now) as it was tricky to figure out how it should properly encode. It might be re-added some time in the future, such as with https://github.com/pillarjs/path-to-regexp/pull/115.
