### ISSUE TITLE
Match everything but root and login

### ISSUE THREAD

**Issue by nschurmann** [pillarjs/path-to-regexp#154]
I'm creating a route that should appear always except at login url, register and the root of the url, but my regexp is not working, any help with it?

`^(?!.*(/|/login|/register)).*$`

it should match everything except `/` `/login` and `/register`

**Comment by worc** [comment]
it's really baffling that there are no working examples of inverse matching for path-to-regexp or react-router. i keep getting stuck writing switch statements instead of something simpler:

`<Route path='/!(login|register)' render={ <LoginButton /> } />`

i wasn't able to get your route working with the [route tester](http://forbeslindesay.github.io/express-route-tester/), but if someone *can* get it working, it'd be a really good addition to the readme.

**Comment by blakeembrey** [comment]
@worc It's probably because there is no inverse path matching for `path-to-regexp` and advanced uses are covered by regexps. If you'd like to provide how it should work, please feel free to propose it.

@nschurmann I'm sorry no one has responded to the issue yet. I tried to tackle it but my regexp knowledge was not good enough, hopefully someone else knows how to construct the regexp properly to negate matching certain paths properly.

**Comment by Fi1osof** [comment]
That does not works too:
`/((topics/.+)|(blog))`

**Comment by blakeembrey** [comment]
@Fi1osof you can just write `/(topics|blog)`, that’s not really related to this issue. There’s no support for nested matching groups in `path-to-regexp`.

**Comment by worc** [comment]
> please feel free to propose it.

what's there to propose? it's just reverse matching.

**Comment by blakeembrey** [comment]
@worc You’d need to describe what the generated regexp looks like, how it might work when combined with regular matches and discuss any edge cases. IIRC, I didn’t manage to get the primary regexp example working. First step is probably to have a working regexp since that would resolve your problem before we build it in.

**Comment by blakeembrey** [comment]
@nschurmann I revisited it just now and found it's possible with the addition of a `$` to suffix match the lookahead: `/^(?!.*(\/|\/login|\/register)$).*$/`.

**Comment by Abishty** [comment]
Try this 

<Route path="/*" render={ ( props ) => ( props.location.pathname !== "/") && <Header /> }/>
                <Route exact path="/" component={LandingPage} />

**Comment by blakeembrey** [comment]
Added a test case for the next major version which supports nested non-capturing groups: https://github.com/pillarjs/path-to-regexp/commit/dcb522f91542ec712a479aa9c721a2b368e03453.
