### ISSUE TITLE
[BUG (?)] Non-consistent behavior

### ISSUE THREAD

**Issue by HelloEdit** [pillarjs/path-to-regexp#160]
I use path-to-regexp in a roundabout way for a project. path-to-regexp broadly analyzes words in a sentence.

The basic options are `{ delimiter: ' ', end: false }`

My problem is, for example, this sentence `hello world`.
If I want to extract just `hello`, pathToRegexp(`:extracthello`, options).exect(string) work well.

But what if I want to extract `hello world` all at once in one argument? I thought adding `+` like `:extracthello+` would work but only `hello` is extracted. I don't know what to do / what configuration to put to have this type of operation.

Thank you in advance,

**Comment by blakeembrey** [comment]
I’m sorry I haven’t gotten around to responding properly yet, I just haven’t had time to properly verify. I suspect it’s the “default delimiter” being used though, you will need to pass both options. I’ll have to think about how to improve this, maybe just erroring when default delimiter is not in the delimiters set.

**Comment by HelloEdit** [comment]
I tried with several delimiters including `" "` and `""`. It does not seem to work

**Comment by blakeembrey** [comment]
I think I found the problem, thanks for bringing this up! It appears to also exist for the regular delimiter `/`. Looking into a proper fix now. Can be replicated with: 

```js
p(':extracthello+', [], { delimiter: '/', delimiters: '/' }).exec('hello/world') //=> null
p('/:extracthello+', [], { delimiter: '/', delimiters: '/' }).exec('/hello/world') //=> [...]
```

It looks like the default `delimiter` is not being used when no delimiter is present. This may have been intentional at some point, but appears to be a pretty big oversight now.

**Comment by HelloEdit** [comment]
Thak you 😄

**Comment by HelloEdit** [comment]
@blakeembrey Hi,

I'm sorry to bother you again, but I have a problem with this issue.
Let's imagine I want to match something lile `:user :reason+` (where reason is optional and, if provided, has to match the rest of the string).

```js
const ptr = require('path-to-regexp')

const regex = ptr(':user :reason', [], { end: false, delimiter: ' ' })

regex.execute('helloedit') // => null
regex.execute('helloedit is me') // => works ('helloedit', 'is me')
```

With all the configurations I have tested, it is impossible to obtain a functional result in all the above situations.

**Comment by HelloEdit** [comment]
I think it's another bug now. Should I open a new issue ?

**Comment by blakeembrey** [comment]
If reason is optional, it should be an asterisk. A plus means “one or more”.

**Comment by HelloEdit** [comment]
```
const ptr = require('path-to-regexp')

const regex = ptr(':user :reason*', [], { end: false, delimiter: ' ' })

regex.exec('helloedit') // => null
regex.exec('helloedit is me') // => works ('helloedit', 'is me')
```
@blakeembrey doesn't work either 😢

**Comment by blakeembrey** [comment]
@HelloEdit You're right, looks like a bug. Taking a look now, thanks!

**Comment by blakeembrey** [comment]
@HelloEdit Actually, ignore that. It's because you haven't set `delimiters`. Both need to be set, since `delimiters` is the list of possible delimiters while `delimiter` is only the default. I might want to fix this up somehow, by throwing when you use a `delimiter` not in the `delimiters` list and/or requiring both options when one is specified.
