### ISSUE TITLE
Suggesion: Re-write in typescript since vast majority of codebase is already in typescript

### ISSUE THREAD

**Issue by somombo** [pillarjs/path-to-regexp#163]
Github says 82.1% of this repo is written in TypeScript. and only 17.9% is JavaScript.

Why not rewrite the `index.js` in typescript so that you can reap the advantage on not having to manually update the definitions file `index.d.ts` (which of course, as things grow, maybe error prone or incomplete).

I noticed `index.js` is only 370 lines so far. The more complex/large the codebase gets the harder this will be in the future.

**Comment by blakeembrey** [comment]
The test suite is the only thing in TypeScript. This library has not been rewritten because it’s used in Express.js and this organisation isn’t designated for first class TypeScript support right now. As it is, if it were rewritten, I’d probably want to tackle it myself to ensure nothing is lost in translation.
