### ISSUE TITLE
encode option for compiled paths throw an error

### ISSUE THREAD

**Issue by ryansukale** [pillarjs/path-to-regexp#177]
See attached screenshot as taken from Runkit in NPM.
That example is copied directly from the Readme.

<img width="635" alt="screen shot 2019-02-09 at 2 55 07 pm" src="https://user-images.githubusercontent.com/755090/52527277-bd980680-2c7a-11e9-99ad-12fc76e61251.png">

**Comment by blakeembrey** [comment]
@ryansukale I'm not sure I follow, this seems like a valid error. You're creating a path that _would not_ be matched by the path (e.g. the path does not match the expected input). What do you expect should happen?

**Comment by blakeembrey** [comment]
You're right that the README seems wrong though! That's my mistake 😄

**Comment by 3den** [comment]
@blakeembrey is there anyway you can allow a decoded param to be injected? e.g.

```js
const path = compile('/my/:anything');
path({anything: 'something/weird&decoded'});
// should return => /my/something/weird&encoded
```

**Comment by blakeembrey** [comment]
@3den I could relax this, but I'd like to understand before I just into breaking anything. It should be noted that, given that returned string parsed with `path-to-regexp` again, it **will not** match. That's what the error is trying to avoid - building a path that wouldn't match. What you can do, if you explicitly want slashes, is a custom regexp _or_ repeated params (e.g. `/:anything(.*)` or `/:anything+`).

**Comment by ellioseven** [comment]
@blakeembrey  I am having difficultly trying to apply what @3den is attempting.

As an example I want to do something like this:

```
const toPath = pathToRegexp.compile("/content/:path");
const p = toPath({ path: "foo/bar/baz" });
console.log(p);
// actual: /content/foo%2Fbar%2Fbaz
// want: /content/foo/bar/baz
```
However the value always seems to be encoded, and as far as I can see, there is no opt-out option?

**Comment by blakeembrey** [comment]
@ellioseven He overrode the `encode` option in his example above. However, you should really just be doing `/:path+` and pass an array value.

**Comment by paulmelnikow** [comment]
I have the same use case @ellioseven mentioned: badges/shields#2649.

As you suggested, `pathToRegexp.compile({ content: 'foo', path: ['bar', 'baz'] })` produces the value I'd like, whereas `pathToRegexp.compile({ content: 'foo', path: 'bar/baz' })` encodes the slash.

Since `pathToRegexp('/:content/:path+').exec('/foo/bar/baz')` produces `["/foo/bar/baz", "foo", "bar/baz"]` it's a bit unexpected that I can't feed the `'/bar/baz'` value back into `pathToRegexp.compile('/:content/:path+')`. There may be a reason this isn't possible, though my expectation is that these operations would be symmetric.

When I'm using a literal, it's possible to use an array, though another spot where I'd like to use this is on user input:

<img width="629" alt="screen shot 2019-02-23 at 2 43 01 pm" src="https://user-images.githubusercontent.com/1487036/53290945-577ea980-3779-11e9-9b7c-7b2f38af4c42.png">

Converting the path to an array of components would be possible, but a bit tricky. Currently I'm working around this by concatenating the strings myself (instead of using `compile`).

**Comment by blakeembrey** [comment]
@paulmelnikow I think your example is more reasonable since that is producing a valid path. The example above from @ellioseven and @3den didn't use a repeated path so the slash would be invalid if it were to be matched again. One thing I'm wary of doing is mixing decoded and encoded values as input params. Another thought is that the input function of a repeated param could split a string input explicitly, then run encode over the results. In this case, something like `foo:bar/bar:baz` would properly encode the colons _and_ keep the slash as valid. If you wanted to explicitly define the params and encode path characters you'd pass an array such as `['foo:bar', 'bar:baz']`. Does this sound reasonable?

Alternatively, I can expose a better matching function and start moving away from `regexp.exec` as an interface. It's honestly not a perfect interface since I also end up building the same sort of matching into my end applications, e.g. https://github.com/blakeembrey/react-route or https://github.com/serviejs/servie-route. Standardizing the match function would enable replacement of any other path matching function too, e.g. a custom function.

**Comment by paulmelnikow** [comment]
Oh, man, I'd love to provide helpful feedback, but since my perspective on this from higher in the stratosphere, I'm a teeny bit lost! 😝 

> One thing I'm wary of doing is mixing decoded and encoded values as input params.

It seems to me the inputs to `pathToRegexp.compile('/:path+').(...)` should always be _unencoded_, with the expectation that the function will encode them.  👍 

> Another thought is that the input function of a repeated param could split a string input explicitly, then run encode over the results. In this case, something like `foo:bar/bar:baz` would properly encode the colons _and_ keep the slash as valid.

I think what you're saying is that `pathToRegexp.compile('/:path+').({ path: 'foo:bar/bar:baz' })` would be `'/foo%3Abar/bar%3Abaz'`. 👍 

> If you wanted to explicitly define the params and encode path characters you'd pass an array such as `['foo:bar', 'bar:baz']`.

That I'm not following.

**Comment by blakeembrey** [comment]
The final point just means that the repeated parameters expects an array input. If you give it the array, it'll encode each parameter and join them by the delimiter automatically. It currently produces the same result as the proposed workaround for when you give it a single string.

Reference: https://github.com/pillarjs/path-to-regexp/blob/4eee1e15ba72d93c996bac4ae649a846eb326562/index.js#L163

**Comment by blakeembrey** [comment]
@paulmelnikow For now, you need to pass path as an array explicitly: `{ path: ['a', 'b', 'c'] }`. Wherever you're currently using this package, you can do that programmatically by implementing the suggested split on `/` (you can get the delimiter from the parsed token).

Changing this logic to the suggestion I made above would be breaking change today 😦 I probably should have just been stricter on the input params and _only_ supported arrays for repeated paths. Then made a separate function that'll preprocess like above. I'll aim for that next release if it sounds reasonable to you.

**Comment by blakeembrey** [comment]
Just a heads up, but there’s a validate option that can be set to false to skip all validation during compilation to string. It should unblock the issues reported here.

**Comment by blakeembrey** [comment]
Fixed example in README with https://github.com/pillarjs/path-to-regexp/commit/dd966ea4f0e6f43f64a97314a1bcd791cfd717bb.

**Comment by dko-slapdash** [comment]
@blakeembrey the main README.md still has this bug in an example:
```
const toPathRaw = compile("/user/:id");
toPathRaw({ id: "%3A%2F" }); //=> "/user/%3A%2F"
... other places too potentially
```

In practice, it returns "/user/%253A%252F" (which is great).

README just needs to be updated, and also it's not toPathRaw anymore.

**Comment by blakeembrey** [comment]
@dko-slapdash No it doesn't. You're probably using a different version to the README:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/1088987/70679188-3e33e480-1c49-11ea-9618-29666bc859e8.png">

**Comment by blakeembrey** [comment]
This was changed in V5: https://github.com/pillarjs/path-to-regexp/releases/tag/v5.0.0

**Comment by dko-slapdash** [comment]
I see. Curious why encodeURIComponent was made turned off by default. It will likely produce a lot of security vulnerabilities in users’ projects, no?

**Comment by blakeembrey** [comment]
@dko-slapdash Can you elaborate on how that would produce a security vulnerability?

I kind of wrote it above, but it's to mirror the way decoding worked. Decoding is also an identity function by default, and it would be confusing if the library couldn't compose `toPath(match('...').params)`.

**Comment by dko-slapdash** [comment]
Makes sense, so there is no choice to make a fully backward compatible change. Either encoding or decoding would diverge. Thanks!
