### ISSUE TITLE
Some thing is great in v1.7.0

### ISSUE THREAD

**Issue by tqma113** [pillarjs/path-to-regexp#196]
I find many people use path-to-regexp with version 1.7.0.They don't want to use the updated version.Maybe they encountered some problem.
I encountered that it can deal with path regexp like `*`. So this can work with version 3.1.0.
```
let reg = pathToRegexp('*')

let result = reg.exec('/any')
```
So, could you add some feature that deleted in upgrade from 1.7.0 to 2.0.0. That will be great.

**Comment by blakeembrey** [comment]
Can you point me to any discussions where this is the sole reason people won’t upgrade? It was removed for a reason.

**Comment by blakeembrey** [comment]
Related to https://github.com/pillarjs/path-to-regexp/pull/115 also.

**Comment by tqma113** [comment]
`react-router` used the 1.7.0 before. I don't mean anything else. I just want to know why these feature has been remove.

**Comment by blakeembrey** [comment]
Because it was never well defined, it was hard to build features like https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp for it. The functionality linked in #115 is similar to how it works in 1.x for most peoples expectations, but it's incompatible with the 1.7 implementation (1.7 works like `.*`, but people expected the compiled params to escape in a particular way).

**Comment by tqma113** [comment]
I got it. Thanks for your response.
