### ISSUE TITLE
Help with pathToRegExp.compile + custom matching parameters

### ISSUE THREAD

**Issue by carolpettirossi** [pillarjs/path-to-regexp#199]
Hi, 

I'm trying to compile a path when it's using a regex to match the param. This is the code:

```
const path = "/:path(graduate-employers/[^/]+)/advice";
const toPathRegexp = pathToRegExp.compile(path)
toPathRegexp({ path: "graduate-employers/abc" }, { validate: true })
```

However, I'm getting this error:

```
TypeError
Expected "path" to match "graduate-employers\/[^\/]+", but got "graduate-employers%2Fabc"
```

I'm pretty sure I'm doing smt wrong. Can someone help me to figure out?

Thanks,
Carol

**Comment by sariag** [comment]
@carolpettirossi the values in the object passed to `toPathRegexp` should not have the delimiter `/` in them, because they get URI encoded i.e. / gets converted to %2F.

You can achieve the same thing like this:
```javascript
const path = "/graduate-employers/:path(.+)/advice";
const toPathRegexp = pathToRegexp.compile(path);
const res = toPathRegexp({ path: 'abc' }, {validate: true});
```

However, if you _must_ pass a value that includes `/` then you can bypass the default encoder by passing your own encoder function, that returns the value as is (not recommended as there is no guarantee it will generate a valid url):
```javascript
const path = "/:path(graduate-employers\/.+)/advice";
const toPathRegexp = pathToRegexp.compile(path);
toPathRegexp({
  path: 'graduate-employers/abc'
}, {
  validate: true,
  encode: (value, token) => value
});
```

**Comment by blakeembrey** [comment]
Applying the change @sariag proposed in https://github.com/pillarjs/path-to-regexp/issues/198 would also resolve this issue and act the same as your expectation here. Encoding of path fragments is a large reason this module needed to move away from being as regexy and more token based.
