### ISSUE TITLE
Options for compile

### ISSUE THREAD

**Issue by frenzzy** [pillarjs/path-to-regexp#215]
```js
const { compile } = require('path-to-regexp')
```
v3 allowed us to compile path once and generate url multiple times with different options:
```js
const url = compile('/:foo')
url({ foo: 'hello+world' }, { encode: encodeURIComponent }) // => "/hello%2Bworld"
url({ foo: 'hello+world' }, { encode: (value) => value })   // => "/hello+world"
```
in v6 this has behavior has been changed and now we have to compile the same path multiple times for each combination of options:
```js
const url = compile('/:foo', { encode: encodeURIComponent })
const prettyUrl = compile('/:foo', { encode: (value) => value })
url({ foo: 'hello+world' })       // => "/hello%2Bworld"
prettyUrl({ foo: 'hello+world' }) // => "/hello+world"
```
it become harder to cache url generation, can we change this back?
from `compile(path, options)(params)` to `compile(path)(params, options)`

**Comment by blakeembrey** [comment]
@frenzzy Could you describe what you're doing that you need to change these options? It won't be changed back, but it could be provided at both steps. The reason it was changed is because libraries should really only configure this once, users of libraries probably don't need or want to changing it with each path they generate - that'll create subtle bugs.

**Comment by frenzzy** [comment]
> Libraries should really only configure this once, users of libraries probably don't need or want to changing it with each path they generate - that'll create subtle bugs

Good point! My tests failed after upgrade, but now I see that I can use instance specific cache instead of global. Thank you!
