### ISSUE TITLE
What caused the size increase?

### ISSUE THREAD

**Issue by StephenTangCook** [pillarjs/path-to-regexp#219]
We haven't updated our npm dependency since v3.0.0 and now at v6.1.0 there is a nontrivial size increase. npm.js reports the unpacked size of 3.2.0 to be [30.9kB](https://www.npmjs.com/package/path-to-regexp/v/3.2.0) and 4.0.0 to be [470kB](https://www.npmjs.com/package/path-to-regexp/v/4.0.0).
Curious what caused the jump?

**Comment by jonchurch** [comment]
It looks to be the way things are compiled w/ Typescript now?

Running `npm pack --dry-run` on v6.1.0 shows the tarball unpacked as 476.3 kB.

v.s. on v3.2.0 it's 30.9kb

Here's a gist w/ the output for each version's `npm pack --dry-run`:
https://gist.github.com/jonchurch/c22c4f87f25377d800967772a55ba4db

I don't honestly know much about typescript, but it appears that the file `src/index.spec.ts` is also included in the build. I assume that is a testing only file, and if that's the case, then it should not be bundled.

Ignoring that file cuts the bundled size down to 109.8 kB unzipped.

**Comment by blakeembrey** [comment]
The NPM pack size will always be a bit misleading here since it counts everything. For example, we publish both ES2015 and CommonJS which also doubles the size. However, the package has grown in size each version it's doing a bit more each time by exposing simpler ways to use the package (e.g. `pathToRegexp` -> `match`).

**Comment by jonchurch** [comment]
Closing as answered, and the pack size has been reduced w/ https://github.com/pillarjs/path-to-regexp/pull/220
