### ISSUE TITLE
Qustion: How to create an optional unknown depth URL path?

### ISSUE THREAD

**Issue by Bigdragon13th** [pillarjs/path-to-regexp#234]
Hi guys, here's my scenario:

I need to build following URLs:

- `/p` => Serve as product list with no filter
- `/p/category` => Serve as product list with category filter
- `/p/category/child-category` => Category can have children
- `/p/category/child-category/...` => Child's category can also have children, and so on

The thing I need from the path is only the slug at the very end, the thing in-between is not important. Here's what I tried:
- `/p/:pathMatch*/:categorySlug` => This is working, except it's not match `/p`
- `/p/:pathMatch*/:categorySlug?` => This match all URLs I need, but instead of given me the last slug in `categorySlug`, it gives me an entire path in `pathMatch` with `categorySlug` always `undefined`

I mean, I can split the `/` from `pathMatch` from the second solution, but if I can done it from the path without code needed in my component would be much better.

**Comment by blakeembrey** [comment]
I think this is a pretty tricky one to define expectations correctly, since the last segment is not different to the repeated inner segments, so I’m going to have to recommend handling the logic in code instead. Example: `constant categorySlug = pathMath.pop()`. Alternatively, use the first example you have that worked and have `/p` by itself be a separate route.
