### ISSUE TITLE
Is it possible to match /:some/:path//// including trailing slashes?

### ISSUE THREAD

**Issue by mpint** [pillarjs/path-to-regexp#266]
Hello, it looks like the default behavior excludes excess trailing backslashes.  I'm getting a `null` match on the following path, but I'd like to include all trailing backslashes.
```
const regexp = pathToRegexp("/:first/:second");

regexp.exec("/some/path////"))

 // [ '/some/path////',  'some',  'path////',  index: 0,  input: '/some/path////',  groups: undefined ]
```

**Comment by blakeembrey** [comment]
This is expected behavior, you can pre-process the URLs with whatever normalization you'd like ahead of time. One example is in the README here where you could replace all repeated slashes with a single slash: https://github.com/pillarjs/path-to-regexp#alternative-using-normalize. The reason it's not part of this library is the pre-processing can be quickly done once to optimize many path matches, instead of every path having to support this and the potential performance implications.
