### ISSUE TITLE
Do not match certain words as parameters with path-to-regexp

### ISSUE THREAD

**Issue by Milutin-P** [pillarjs/path-to-regexp#268]
I have a route `/:parameter` and if someone pings that route I should serve him certain page (React App)
So what I need is some kind of regexp that wont match certain words...

Regular expression should be `^(?!.*(foobar1|\/foobar2)).*$`

https://pshrmn.github.io/route-tester/#/ I've used this tool for testing and entered various combinations, such as `/parameter(?!.*(foobar1|\/foobar2))` but no luck...

So test case should be 

if path is `/foobar3` it should return page
if path is `/foobar2` or `/foobar3` it should return `null`

**Comment by tigt** [comment]
Does [“the best regex trick”](http://www.rexegg.com/regex-best-trick.html) work for your needs? I think it would express your example as `/(?:foobar2|foobar3|(foobar1))/`, but I admit I couldn’t figure out how to translate it into a form that the linked route-tester page was happy with.

**Comment by juanmagalhaes** [comment]
+1 here. I'm facing the same issue right now.

**Comment by blakeembrey** [comment]
If someone wants to propose expanding the existing syntax to support this, I'm happy to review.

Otherwise I'd suggest maybe filing a ticket with the libraries using this package to support this feature. It's definitely easier than trying to construct a negative regex. For example, in something like Express you can have middleware that runs and write a line of code that says `parameter !== 'foobar1'` to skip the middleware on that condition.

**Comment by Seunfola** [comment]
I think you should define the parameters for the dynamic route then use the logic to return the page

const isExcluded = /^(?!foobar1$|foobar2$).+/.test(parameter);
  
  if (!isExcluded) {
    return null; 
  }

**Comment by blakeembrey** [comment]
Closing this out as V8 does not support custom regexes, and I would recommend that libraries provide an ability to `exclude` paths rather than require complex regexes. However, in versions prior to V8 you can achieve this with a negative lookahead, something like `/:foo((?!xyz).+)`, where you want to match anything that doesn't start with `xyz`.
