### ISSUE TITLE
Issue with converted value used in Next.js rewrite

### ISSUE THREAD

**Issue by leog** [pillarjs/path-to-regexp#304]
Hello community!

Using the following source value for a Next.js rewrite, which is valid and works locally, it doesn’t work when built and deployed.

```"/:path((?!api|auth|_next/static|_next/image|favicon.ico).*)"```

The intention for this value is to catch the entire path which shouldn't match Next.js internal resources.

The entire rewrite is the following:

```
{
    source: "/:path((?!api|auth|_next/static|_next/image|favicon.ico).*)",
    has: [
      {
        type: "host",
        value:"subdomain.com",
      },
    ],
    destination: `/subdomain/:path*`,
  }
```

The error I get is the following:

> Expected "path" to match "[^\/#\?]+?", but got ""

And the converted value for the troubled value is this one, which refers to the previous error:

```/^(?:\/((?!api|auth|_next\/static|_next\/image|favicon.ico).*))[\/#\?]?$/i```

Any help would be greatly appreciated.

**Comment by leog** [comment]
Adding more info to this, I think the issue arises when the path is actually an empty string (as in the root of the website) and because of the `+` [in this line](https://github.com/pillarjs/path-to-regexp/blob/80a1eb6c5dd32e3f61f4f6fcbce74ef2adaa9a69/src/index.ts#L143) it is assumed to be incorrect when matching later with `options.validate: true` as opposed to a successful run on development where `options.validate: false` is set.

Is there any way that`defaultPattern` be something else for these cases? I would hate to have to fork, fix it in my fork and force Next.js to use that version.

Thanks a lot in advance.

**Comment by blakeembrey** [comment]
I have a pretty good guess but aren't 100% sure without spelunking into next.js source code and replicating what you're doing. I assume you're trying to load `/` or even just a blank URL, hence the `""`? And that doesn't match the regex expected, hence the error. The code path is here: https://github.com/pillarjs/path-to-regexp/blob/80a1eb6c5dd32e3f61f4f6fcbce74ef2adaa9a69/src/index.ts#L324-L326.

Basically it's trying to do things via type checking and optional expected `null` or an empty array in this case. 

One workaround, since this is being used in a way I hadn't really designed it for (which, btw, is very awesome to see) is to use `/subdomain/:path(.*)` as the destination. That should change the regex check. Another option is for next.js to set `validate` to `false`.

I would love to involve anyone from next.js if they're interested in collaborating on a longer term solution.

**Comment by leog** [comment]
> One workaround, since this is being used in a way I hadn't really designed it for (which, btw, is very awesome to see) is to use /subdomain/:path(.*) as the destination.

@blakeembrey that made the trick! thank you!

Found [this](https://github.com/vercel/next.js/pull/15231/files#diff-42054d7ab430b986d5a4ab155dfa42732cd90362f2168fd8aff6d0b32af464abR55) in their codebase about their usage of `validate` equaling `false`, you must have too, but just in case this triggers collaboration with Next.js team, which BTW, was worked on by @timneutkens and @ijjk to see if there is any interest on such a collaboration.

Thanks again @blakeembrey!
