### ISSUE TITLE
Path wildcards

### ISSUE THREAD

**Issue by recidive** [pillarjs/path-to-regexp#37]
I was using pathRegexp() from from Express utils, but since this was removed in 4, I had to migrate to path-to-regexp. I was using it to match an URL only (to get the context for a page) not actually using parameters.

The problem is that /some-path/\* URLs stopped working and I need to change it across all the application to use /some-path/(.*).

Since this is an application to be used also by non programmers, /some-path/\* would be more straightforward.

Do you have any plans to bring back /some-path/\* at some point?

**Comment by andineck** [comment]
I ran into this problem as well, and it took me a while to find the reason for this unexpected behaviour, since page.js docs are not reflecting the current behaviour.

I just checked express.js deps again:     
"path-to-regexp": "0.1.3",

I really think the current version where wildcard does not work anymore as it does in express.js is very confusing for the user. regex is not everyone's favourite and it makes things not very readable. 

I can understand, the ambiguity in the implementation, but I would definitively prefer a consistent (as it has been for a while) and simple use of the module, over a simple implementation of the module itself.

**Comment by blakeembrey** [comment]
@andineck I understand the concern, but there shouldn't be a case where you need to use `*`. Could you give a code snippet where you use it? In 99% of cases, you should be using `.use` in Express.js which is also a slight optimisation since you don't need to do path matching. For everything else, you can use a regular expression which, I think, is much clearer about the intention. I understand it doesn't make things very readable, but I also don't think `*` is any more readable than `/:path*` - the latter even gives you a key name. Also, the asterisk behaviour was largely undefined. For instance, it just expanded to `(.*)` which made key indexes are to keep in `0.1.x`, and it can cause unexpected behaviour. For example, `/user/:path*/foo` will match `/user/123/foo` but `/user/*` will match the same except it can match `/user//foo` since it's just a zero or more matching group. The expansion syntax is a little more complex in that it'll actually take into account what the path looks like.

**Comment by andineck** [comment]
I'm not saying there is a use case that could not be solved with `(.*)` instead of  `*`.

I am using express.Router on the server side, and page.js in the browser.
Now page.js switched to the new version, express sticks with 0.1.3 (strict).

my path is `/upload/*` and it is matching e.g. '/upload/img/small'
I am not saying this use case could be rewritten to something like `/upload/(.*)` or `/upload/:path*`,
but I also don't think these are more readable than `/upload/*`

The `*` was not documented in the best way, but it is documented after all:

Express:
 - http://expressjs.com/4x/api.html#req.params
 - http://expressjs.com/4x/api.html#router.all

Page.js:
 - https://github.com/visionmedia/page.js/blob/master/Readme.md (all over the place)


The confusion got even bigger, since page.js uses this to mimic the old `*` behaviour (but only for straight `*` and not for things like `/api/*` with the introduction of this line:
``` this.path = (path === '*') ? '(.*)' : path;```

Personally I think the old version 0.1.3 was simpler to use, and I wish that one could agree on a api, since it is not fun to change this in various places with an updage.
I wonder why express.js is sticking to the version 0.1.3. @dougwilson ?
What's the plan with page.js @shuvalov-anton ?

**Comment by blakeembrey** [comment]
You're right. Maybe it can be added back for a little more consistency because I do see it used as a common example everywhere. I expect it to act like the new `(.*)` though, so it won't be backward compatible with the old behaviour. Also, it won't replace inside of a matching group (E.g. `:file(*)` won't expand to `:file(.*)`). 

The reason it hasn't been updated in Express.js is because it's a breaking change and needs to wait for `5.x`.

**Comment by blakeembrey** [comment]
@andineck If you have a chance, please review https://github.com/pillarjs/path-to-regexp/pull/54.
