### ISSUE TITLE
Impossible to compile to + and *

### ISSUE THREAD

**Issue by klimashkin** [pillarjs/path-to-regexp#58]
```
var toPath = pathToRegexp.compile('/goods/:splat+')
var result = toPath({ splat: '1/all' })  //error

var toPath = pathToRegexp.compile('/goods/:splat(.+)')
var result = toPath({ splat: '1/all' })
console.log(result) //=> "/goods/1%2Fall"
```

**Comment by blakeembrey** [comment]
I guess this isn't 100% right now. The issue is that it shouldn't have a slash in the path. If you want a slash with that, you need to pass an array like `{ splat: [1, 'all'] }`.

However, that begs the question of whether encoding it as I currently do is the correct behaviour since there would be no way to input an encoded slash right now. Perhaps either encoding it before validation or removing encoding?

**Comment by IsaiahJTurner** [comment]
I think this is the same issue I am experiencing but I'm not sure. I want to define a route like `/:postType(video|audio|text)?+*` that will match `/video`, `/audio`, and `/video+someTextString. Basically, treating the plus sign as an alias. The closest working alternative I've found is ``/:postType(video|audio|text)?\\+*` but for some reason that won't match URLs that do not contain a plus sign.

**Comment by blakeembrey** [comment]
@IsaiahJTurner It looks like a different issue. Plus signs that are by themselves have no semantic effect, it's just a plus sign. The match you are doing results with `/^(?:\/(video|audio|test))?\+(.*)(?:\/(?=$))?$/i`. Notice the plus sign that must be matched in the middle. Not sure what the difference between your two examples are though, they should be treated exactly the same.

I don't have a perfect solution for you with this. Either you can add a plus sign as `video+|audio+|text+`, or you could use an array of matches (probably preferable) like `['/:postType(video|audio|text)+*', '/*']`.
