### ISSUE TITLE
help: Handling parentheses in the path pattern not related prefixes

### ISSUE THREAD

**Issue by whitlockjc** [pillarjs/path-to-regexp#76]
I currently use `path-to-regexp` in Sway and a user reported [an issue](https://github.com/apigee-127/sway/issues/79) that I believe will require me to do a little escaping prior to calling `path-to-regexp`.  The user is currently trying to create an OData path like `/Users(:id)` but a request path of `/Users(1)` does not match the regex where I would expect it to.  Now, I realize the reason for this is that parentheses are special but before I just go blindly escaping/hacking this to work, I wanted to get your opinion on how best to handle this situation.

**Note:** OpenAPI/Swagger use bracket-based variable naming in paths so in the linked issue you'll see `/Users({id})` instead of `/Users(:id)`.  Do not let this trip you up because I already handle converting OpenAPI/Swagger paths to Express-style paths.  Also, OpenAPI/Swagger paths do not allow regex in their path pattern _(in case that matters with suggesting a solution)_.

**Comment by blakeembrey** [comment]
Understood 😄 I actually wrote most of the RAML tooling for Node.js, so I'm also aware of this. Personally, I went and implemented my own path matcher and opened a PR to the Express.js router to make it extensible in 5.0. However, that's just an FYI since you asked for the best solution, and building a custom matcher would be best (but is not really available in Express.js today until, at least, `router@2.0` is released). Would you be interested in using this approach? (I wouldn't mind spending some time exposing this work for you to re-use, I can also link to anything RAML-related which solved the same problems).

In terms of today, and if you want to continue mapping to current Express.js-compatible paths, you'll need to escape any special characters `path-to-regexp` has. Just be aware that although the current `path-to-regexp` is `1.x` and has a lot of improved features, current Express.js uses `0.1.x` and has a few quirks when it comes to matching.

**Comment by whitlockjc** [comment]
Is there a list of special characters?  I am sure I can figure it out by code grokking but if you already know, or want to mention it for posterity.

**Comment by blakeembrey** [comment]
Sure. Of the top of my head, I believe it's `(`, `)`, `:`, `*`, `+` and `?`.

**Comment by whitlockjc** [comment]
Thanks @blakeembrey.  As for my being interested in you breaking out the reusable stuff from your RAML work, I'd love to help out.  I'm all for helping the community.

**Comment by blakeembrey** [comment]
@whitlockjc Most of the work come from Osprey (https://github.com/mulesoft/osprey) which mostly involved a bit of refactoring of the router (https://github.com/pillarjs/router/pull/29) to support custom path handlers, at which point I wrote https://github.com/mulesoft-labs/raml-path-match. I've been meaning to correct that router and release it separately so more people can actually use it, but the PR's been around for almost a year and a half now 

/cc @dougwilson

**Comment by blakeembrey** [comment]
Closing this since the issue here was answered. You can escape `path-to-regexp` special characters with `\\`.
