### ISSUE TITLE
patterns with once or more `+` is broken

### ISSUE THREAD

**Issue by magicdawn** [pillarjs/path-to-regexp#81]
version 1.4.0

```js
> p = require('path-to-regexp')
{ [Function: pathToRegexp]
  parse: [Function: parse],
  compile: [Function: compile],
  tokensToFunction: [Function: tokensToFunction],
  tokensToRegExp: [Function: tokensToRegExp] }
> p('/:foo+').exec('/foo/bar')
[ '/foo/bar', 'foo/bar', index: 0, input: '/foo/bar' ]
> p('/:foo+baz').exec('/foo/barbaz')
null
> p('/:foo+')
{ /^\/((?:[^\/]+?)(?:\/(?:[^\/]+?))*)(?:\/(?=$))?$/i
  keys:
   [ { name: 'foo',
       prefix: '/',
       delimiter: '/',
       optional: false,
       repeat: true,
       pattern: '[^\\/]+?' } ] }
> p('/:foo+baz')
{ /^\/((?:[^\/]+?)(?:(?:[^\/]+?))*)baz(?:\/(?=$))?$/i
  keys:
   [ { name: 'foo',
       prefix: '',
       delimiter: '/',
       optional: false,
       repeat: true,
       pattern: '[^\\/]+?' } ] }
>
```

`p('/:foo+baz')` should results /^\/((?:[^\/]+?)(?:`\/`(?:[^\/]+?))*)baz(?:\/(?=$))?$/i
the `\/` is missing

**Comment by magicdawn** [comment]
I used `^1.2.1`, and installed with `^1.4.0`, things are broken.
if it's not compatible with old version, please bump major version

```
p('/:foo+baz').exec('/foo/barbaz')
```

works on `1.2.x`. `1.3.x` & `1.4.x` are broken.

**Comment by blakeembrey** [comment]
The `\/` is there, it's at the beginning. The issue stems from the fixes for the segment matching behaviour. Before I make a new change to this, I'll need to think about it and the uses. There's some docs documenting this: https://github.com/pillarjs/path-to-regexp#named-parameters.

For example, the old behaviour was breaking on `/:foo?-bar` because the `/` was part of the match - so it'd match `/a-bar` or just `-bar` without any slash. Unfortunately that didn't make a ton of sense. Perhaps this can match `/` or the match. I'm going to try that implementation now 😄
